os: linux
dist: xenial
sudo: true

language: python
cache: pip

python:
  - "3.7"
  # - "3.6"
  # - "3.5"
  # - "3.4"   # not available for xenial
  - "2.7"

before_install:
  - sudo apt-get install -y git mercurial
  - sudo bash build_wheel_on_travis.sh

install:
  - pip install $(cat requirements-test.txt)

script:
  - python --version
  - python -m flake8 src/pycalver/

  - export MYPYPATH=stubs/
  - python -m mypy src/pycalver/

  - export PYTHONPATH=src/:$PYTHONPATH
  - python -m pytest --cov=pycalver test/
  - codecov

  - rst2html5 --strict README.rst > /dev/null
  - rst2html5 --strict CHANGELOG.rst > /dev/null
