os: linux
dist: xenial
sudo: true

language: python
cache: pip

python:
  - "3.7"
  # - "3.6"
  # - "3.5"
  # - "3.4"   # not available for xenial
  - "2.7"

before_install:
  - curl -sSf -o python-3.7.tar.bz2 https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/16.04/x86_64/python-3.7.tar.bz2
  - sudo tar xjf python-3.7.tar.bz2 --directory /
  - sudo apt-get install -y git mercurial
  - python3.7 -m pip install lib3to6


install:
  - pip install $(cat requirements-test.txt)
  - python3.7 setup.py bdist_wheel --python-tag=py2.py3

script:
  - python --version
  - python3.7 --version
  - python -m flake8 src/pycalver/

  - export MYPYPATH=stubs/
  - python -m mypy src/pycalver/

  - export PYTHONPATH=src/:$PYTHONPATH
  - python -m pytest --cov=pycalver test/
  - codecov

  - rst2html5 --strict README.rst > /dev/null
  - rst2html5 --strict CHANGELOG.rst > /dev/null
