os: linux

language: python
cache: pip

before_install:
  - uname
  - sudo apt-get install -y git mercurial
  - sudo bash travis_build_wheel.sh

script:
  - python --version
  - bash travis_run_tests.sh


matrix:
  include:
  - python: "3.6"
  - python: "3.5"
  - python: "3.4"
  - python: "2.7"
  - python: "pypy3.5"
  - python: "pypy2.7"
  - python: "3.7"
    dist: xenial
    sudo: true
