os: linux
dist: xenial
sudo: true

language: python
cache: pip

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

before_install:
  - apt-get install -y git mercurial
  - apt-get install -y python3.7
  - python3.7 -m pip install lib3to6
  - python3.7 setup.py bdist_wheel --python-tag=py2.py3


install:
  - pip install $(cat requirements-test.txt)
  - pip install .

script:
  - python -m flake8 src/pycalver/

  - export MYPYPATH=stubs/
  - python -m mypy src/pycalver/

  - export PYTHONPATH=src/:$PYTHONPATH
  - python -m pytest --cov=pycalver test/
  - codecov

  - rst2html5 --strict README.rst > /dev/null
  - rst2html5 --strict CHANGELOG.rst > /dev/null
