os: linux
dist: xenial
sudo: true

language: python
cache: pip

python:
  - "3.7"
  # - "3.6"
  # - "3.5"
  # - "3.4"   # not available for xenial
  - "2.7"

before_install:
  - sudo apt-get install -y git mercurial
  - sudo bash travis_build_wheel.sh

script:
  - python --version
  - bash travis_run_tests.sh
